"""Wheeliometer analysis package."""

from .imu_binary_parser import (
    IMU_FILE_MAGIC,
    BinaryParseError,
    FileHeader,
    ImuSample,
    ParsedImuFile,
    parse_imu_file,
    read_imu_header,
    iter_imu_samples,
)
from .orientation_fusion import (
    IDENTITY_MATRIX_3X3,
    OrientationSample,
    fuse_orientation,
    PoseSample,
    fuse_pose,
    mat3_mul_vec,
    parse_sensor_to_body_matrix,
    quat_to_rotation_matrix,
    pose_matrix_4x4,
    rotate_vector,
    rotation_matrix_4x4,
    select_frame_indices,
    validate_sensor_to_body_matrix,
)

__all__ = [
    "IMU_FILE_MAGIC",
    "BinaryParseError",
    "FileHeader",
    "ImuSample",
    "ParsedImuFile",
    "parse_imu_file",
    "read_imu_header",
    "iter_imu_samples",
    "IDENTITY_MATRIX_3X3",
    "OrientationSample",
    "fuse_orientation",
    "PoseSample",
    "fuse_pose",
    "mat3_mul_vec",
    "parse_sensor_to_body_matrix",
    "quat_to_rotation_matrix",
    "pose_matrix_4x4",
    "rotate_vector",
    "rotation_matrix_4x4",
    "select_frame_indices",
    "validate_sensor_to_body_matrix",
]
